# Generated by Django 2.0.2 on 2018-04-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='api_key',
            field=models.CharField(max_length=255, unique=True, verbose_name='API Key'),
        ),
    ]
