# Generated by Django 2.0.2 on 2018-05-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0002_auto_20180427_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Chat id'),
        ),
    ]
