# Generated by Django 2.0.2 on 2018-06-11 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0003_auto_20180530_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegramuser', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
